2024-12-06 18:42:51,061 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "E:\MyProgInUrban\VitalyDegtyarev_pythonProject_M12\tests_12_4.py", line 32, in test_run
    runner2 = Runner(1, 10)
              ^^^^^^^^^^^^^
  File "E:\MyProgInUrban\VitalyDegtyarev_pythonProject_M12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-06 18:42:51,062 | WARNING | Неверная скорость для объекта Runner
Traceback (most recent call last):
  File "E:\MyProgInUrban\VitalyDegtyarev_pythonProject_M12\tests_12_4.py", line 22, in test_walk
    runner1 = Runner('Oleg', -1)
              ^^^^^^^^^^^^^^^^^^
  File "E:\MyProgInUrban\VitalyDegtyarev_pythonProject_M12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
